baseURL = "https://dayio.dev/"
languageCode = "en-us"
title = "Dayio.dev"
theme = "archie"
copyright = "© Dayio"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 5 # articles per page

[services]
[services.disqus]
shortname = 'dayio'

[params]
    author = "Alexandre Mangin"
    authorAlternate = "Dayio"
    description = "Exploring tech from the cloud down to the hardware level"
    og_image = "images/og-card.png" # You should create this image in static/images/
mode = "toggle"
useCDN = true
subtitle = "Exploring tech from the cloud down to the hardware level"
mathjax = true
katex = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/dayio"

[[menu.main]]
name = "~/"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
